const express = require('express')
const taskRouter = require('./router/tasks')
const labelRouter = require('./router/labels')
const cors = require('cors')
const app = express()

app.use(cors())
app.use(express.json())
app.use('/tasks', taskRouter)
app.use('/labels', labelRouter)
app.listen(5000, () => console.log('server listening on port 5000...'))
